### PR TITLE
Simple docker config

### PR DESCRIPTION
**Pull request by n0um3n4**
### What does this PR do?

* Adds a simple docker configuration.
* A few gems for lint, code smells and other misdemeanors.

### CODE REVIEW

**Comment by n0um3n4** [comment]
@kurenn delete if this gem is discontinued. delete repo not just branch, please.

**Comment by kurenn** [comment]
It does not receive support, not sure if we should delete it as  it works for the CIC, but not too sure, should we erase it?

**Comment by n0um3n4** [comment]
Gotcha. Hmm then let me see if we can do something more, refactors, etc. Updates and such.

**Comment by kurenn** [comment]
Yeah, thanks for the catch up!

**Pull request closed without merging**
